// Code generated by protoc-gen-go from "haproxy.proto"
// DO NOT EDIT!

package haproxy2pb

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Request_Reason int32

const (
	Request_CLIENT_ABORT   Request_Reason = 1
	Request_SERVER_ABORT   Request_Reason = 2
	Request_PROXY_ABORT    Request_Reason = 3
	Request_RESOURCE_LIMIT Request_Reason = 4
	Request_INTERNAL_ERROR Request_Reason = 5
	Request_CLIENT_TIMEOUT Request_Reason = 6
	Request_SERVER_TIMEOUT Request_Reason = 7
)

var Request_Reason_name = map[int32]string{
	1: "CLIENT_ABORT",
	2: "SERVER_ABORT",
	3: "PROXY_ABORT",
	4: "RESOURCE_LIMIT",
	5: "INTERNAL_ERROR",
	6: "CLIENT_TIMEOUT",
	7: "SERVER_TIMEOUT",
}
var Request_Reason_value = map[string]int32{
	"CLIENT_ABORT":   1,
	"SERVER_ABORT":   2,
	"PROXY_ABORT":    3,
	"RESOURCE_LIMIT": 4,
	"INTERNAL_ERROR": 5,
	"CLIENT_TIMEOUT": 6,
	"SERVER_TIMEOUT": 7,
}

func NewRequest_Reason(x Request_Reason) *Request_Reason {
	e := Request_Reason(x)
	return &e
}
func (x Request_Reason) String() string {
	return proto.EnumName(Request_Reason_name, int32(x))
}

type Request_ProxyState int32

const (
	Request_REQUEST    Request_ProxyState = 1
	Request_QUEUE      Request_ProxyState = 2
	Request_CONNECTION Request_ProxyState = 3
	Request_HEADERS    Request_ProxyState = 4
	Request_DATA       Request_ProxyState = 5
	Request_LAST       Request_ProxyState = 6
	Request_TARPIT     Request_ProxyState = 7
)

var Request_ProxyState_name = map[int32]string{
	1: "REQUEST",
	2: "QUEUE",
	3: "CONNECTION",
	4: "HEADERS",
	5: "DATA",
	6: "LAST",
	7: "TARPIT",
}
var Request_ProxyState_value = map[string]int32{
	"REQUEST":    1,
	"QUEUE":      2,
	"CONNECTION": 3,
	"HEADERS":    4,
	"DATA":       5,
	"LAST":       6,
	"TARPIT":     7,
}

func NewRequest_ProxyState(x Request_ProxyState) *Request_ProxyState {
	e := Request_ProxyState(x)
	return &e
}
func (x Request_ProxyState) String() string {
	return proto.EnumName(Request_ProxyState_name, int32(x))
}

type Request_Cookie int32

const (
	Request_NO      Request_Cookie = 1
	Request_INVALID Request_Cookie = 2
	Request_DOWN    Request_Cookie = 3
	Request_VALID   Request_Cookie = 4
	Request_EXPIRED Request_Cookie = 5
	Request_OLD     Request_Cookie = 6
)

var Request_Cookie_name = map[int32]string{
	1: "NO",
	2: "INVALID",
	3: "DOWN",
	4: "VALID",
	5: "EXPIRED",
	6: "OLD",
}
var Request_Cookie_value = map[string]int32{
	"NO":      1,
	"INVALID": 2,
	"DOWN":    3,
	"VALID":   4,
	"EXPIRED": 5,
	"OLD":     6,
}

func NewRequest_Cookie(x Request_Cookie) *Request_Cookie {
	e := Request_Cookie(x)
	return &e
}
func (x Request_Cookie) String() string {
	return proto.EnumName(Request_Cookie_name, int32(x))
}

type Request_CookieTransform int32

const (
	Request_NONE      Request_CookieTransform = 1
	Request_INSERTED  Request_CookieTransform = 2
	Request_UPDATED   Request_CookieTransform = 3
	Request_PROVIDED  Request_CookieTransform = 4
	Request_REWRITTEN Request_CookieTransform = 5
	Request_DELETED   Request_CookieTransform = 6
)

var Request_CookieTransform_name = map[int32]string{
	1: "NONE",
	2: "INSERTED",
	3: "UPDATED",
	4: "PROVIDED",
	5: "REWRITTEN",
	6: "DELETED",
}
var Request_CookieTransform_value = map[string]int32{
	"NONE":      1,
	"INSERTED":  2,
	"UPDATED":   3,
	"PROVIDED":  4,
	"REWRITTEN": 5,
	"DELETED":   6,
}

func NewRequest_CookieTransform(x Request_CookieTransform) *Request_CookieTransform {
	e := Request_CookieTransform(x)
	return &e
}
func (x Request_CookieTransform) String() string {
	return proto.EnumName(Request_CookieTransform_name, int32(x))
}

type Request struct {
	Host                       *string                   `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Process                    *string                   `protobuf:"bytes,2,req,name=process" json:"process,omitempty"`
	Pid                        *int32                    `protobuf:"varint,3,req,name=pid" json:"pid,omitempty"`
	ClientIp                   []byte                    `protobuf:"bytes,4,req,name=client_ip" json:"client_ip,omitempty"`
	ClientPort                 *uint32                   `protobuf:"varint,5,req,name=client_port" json:"client_port,omitempty"`
	Year                       *uint32                   `protobuf:"varint,6,req,name=year" json:"year,omitempty"`
	Month                      *uint32                   `protobuf:"varint,7,req,name=month" json:"month,omitempty"`
	Day                        *uint32                   `protobuf:"varint,8,req,name=day" json:"day,omitempty"`
	Hour                       *uint32                   `protobuf:"varint,9,req,name=hour" json:"hour,omitempty"`
	Minute                     *uint32                   `protobuf:"varint,10,req,name=minute" json:"minute,omitempty"`
	Second                     *uint32                   `protobuf:"varint,11,req,name=second" json:"second,omitempty"`
	NanoSecond                 *uint32                   `protobuf:"varint,12,req,name=nano_second" json:"nano_second,omitempty"`
	Frontend                   *string                   `protobuf:"bytes,13,req,name=frontend" json:"frontend,omitempty"`
	Backend                    *string                   `protobuf:"bytes,14,req,name=backend" json:"backend,omitempty"`
	Server                     *string                   `protobuf:"bytes,15,req,name=server" json:"server,omitempty"`
	TimeQueue                  *int32                    `protobuf:"varint,16,opt,name=time_queue" json:"time_queue,omitempty"`
	TimeWait                   *int32                    `protobuf:"varint,17,opt,name=time_wait" json:"time_wait,omitempty"`
	TimeConnect                *int32                    `protobuf:"varint,18,opt,name=time_connect" json:"time_connect,omitempty"`
	TimeRespond                *int32                    `protobuf:"varint,19,opt,name=time_respond" json:"time_respond,omitempty"`
	TimeTotal                  *int32                    `protobuf:"varint,20,opt,name=time_total" json:"time_total,omitempty"`
	StatusCode                 *int32                    `protobuf:"varint,21,opt,name=status_code" json:"status_code,omitempty"`
	BytesRead                  *int32                    `protobuf:"varint,22,opt,name=bytes_read" json:"bytes_read,omitempty"`
	RequestCookie              *string                   `protobuf:"bytes,23,opt,name=request_cookie" json:"request_cookie,omitempty"`
	ResponseCookie             *string                   `protobuf:"bytes,24,opt,name=response_cookie" json:"response_cookie,omitempty"`
	TerminationReason          *Request_Reason           `protobuf:"varint,25,opt,name=termination_reason,enum=haproxy.Request_Reason" json:"termination_reason,omitempty"`
	TerminationState           *Request_ProxyState       `protobuf:"varint,26,opt,name=termination_state,enum=haproxy.Request_ProxyState" json:"termination_state,omitempty"`
	TerminationCookie          *Request_Cookie           `protobuf:"varint,27,opt,name=termination_cookie,enum=haproxy.Request_Cookie" json:"termination_cookie,omitempty"`
	TerminationCookieTransform *Request_CookieTransform  `protobuf:"varint,28,opt,name=termination_cookie_transform,enum=haproxy.Request_CookieTransform" json:"termination_cookie_transform,omitempty"`
	ActiveConnections          *int32                    `protobuf:"varint,29,opt,name=active_connections" json:"active_connections,omitempty"`
	FrontendConnections        *int32                    `protobuf:"varint,30,opt,name=frontend_connections" json:"frontend_connections,omitempty"`
	BackendConnections         *int32                    `protobuf:"varint,31,opt,name=backend_connections" json:"backend_connections,omitempty"`
	ServerConnections          *int32                    `protobuf:"varint,32,opt,name=server_connections" json:"server_connections,omitempty"`
	Retries                    *int32                    `protobuf:"varint,33,opt,name=retries" json:"retries,omitempty"`
	ServerQueue                *int32                    `protobuf:"varint,34,opt,name=server_queue" json:"server_queue,omitempty"`
	BackendQueue               *int32                    `protobuf:"varint,35,opt,name=backend_queue" json:"backend_queue,omitempty"`
	RequestHeaders             []string                  `protobuf:"bytes,36,rep,name=request_headers" json:"request_headers,omitempty"`
	ResponseHeaders            []string                  `protobuf:"bytes,37,rep,name=response_headers" json:"response_headers,omitempty"`
	HttpMethod                 *string                   `protobuf:"bytes,38,opt,name=http_method" json:"http_method,omitempty"`
	HttpUri                    *string                   `protobuf:"bytes,39,opt,name=http_uri" json:"http_uri,omitempty"`
	HttpVersion                *string                   `protobuf:"bytes,40,opt,name=http_version" json:"http_version,omitempty"`
	XXX_extensions             map[int32]proto.Extension `json:",omitempty"`
	XXX_unrecognized           []byte                    `json:",omitempty"`
}

func (this *Request) Reset()         { *this = Request{} }
func (this *Request) String() string { return proto.CompactTextString(this) }

var extRange_Request = []proto.ExtensionRange{
	{1000, 536870911},
}

func (*Request) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Request
}
func (this *Request) ExtensionMap() map[int32]proto.Extension {
	if this.XXX_extensions == nil {
		this.XXX_extensions = make(map[int32]proto.Extension)
	}
	return this.XXX_extensions
}

func init() {
	proto.RegisterEnum("haproxy.Request_Reason", Request_Reason_name, Request_Reason_value)
	proto.RegisterEnum("haproxy.Request_ProxyState", Request_ProxyState_name, Request_ProxyState_value)
	proto.RegisterEnum("haproxy.Request_Cookie", Request_Cookie_name, Request_Cookie_value)
	proto.RegisterEnum("haproxy.Request_CookieTransform", Request_CookieTransform_name, Request_CookieTransform_value)
}
